---
- name: lean_delivery.java
  src: https://github.com/lean-delivery/ansible-role-java
  version: 7.2.5
- src: geerlingguy.postgresql
  version: 3.4.2
- src: jdauphant.ssl-certs
  version: v1.7.1
- src: nginxinc.nginx
  version: 0.23.2
