---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-sonarqube
      sonar_major_version: 8
      sonar_minor_version: 8.0.42792
      sonar_install_optional_plugins: true
      sonar_set_jenkins_webhook: true
      sonar_restore_profiles: true
      sonar_web_password: your_new_secure_password
      change_password: true
      sonar_web_old_password: admin
