---
inputs:
  name:
    description: 'Your name'
    default: 'No name provided'
runs:
  using: "composite"
  steps:
    - run: |
        ansible --version
        ansible-lint --version
        molecule --version
        rm -rf molecule/resources/provisioning
        git clone https://github.com/lean-delivery/ansible-molecule-drivers.git molecule/resources/provisioning
        pip install jmespath
        apk add --no-cache docker # temp fix
      shell: bash
