---
- name: Get webhooks list
  ansible.builtin.uri:
    url: '{{ sonar_check_url }}/api/webhooks/list'
    method: GET
    force_basic_auth: true
    user: '{{ sonar_web_user }}'
    password: '{{ sonar_web_password }}'
    validate_certs: false
    return_content: true
  register: webhooks_list

- name: Get jenkins webhook key
  ansible.builtin.set_fact:
    webhook_key: '{{ item }}'
  loop: '{{ webhooks_list | json_query(webhook_name_query) }}'
  vars:
    webhook_name_query: "json.webhooks[?name=='{{ sonar_jenkins_webhook_name }}'].key"

- name: Create jenkins webhook
  ansible.builtin.uri:
    url: '{{ sonar_check_url }}/api/webhooks/create'
    method: POST
    force_basic_auth: true
    user: '{{ sonar_web_user }}'
    password: '{{ sonar_web_password }}'
    body: 'name={{ sonar_jenkins_webhook_name }}&url={{ sonar_jenkins_webhook_url }}'
    body_format: form-urlencoded
    validate_certs: false
  when:
    - webhook_key is undefined

- name: Update jenkins webhook
  ansible.builtin.uri:
    url: '{{ sonar_check_url }}/api/webhooks/update'
    method: POST
    force_basic_auth: true
    user: '{{ sonar_web_user }}'
    password: '{{ sonar_web_password }}'
    body: 'name={{ sonar_jenkins_webhook_name }}&url={{ sonar_jenkins_webhook_url }}&webhook={{ webhook_key }}'
    body_format: form-urlencoded
    validate_certs: false
    status_code: 204
  when:
    - webhook_key is defined
