---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: ec2
lint: |
  yamllint
  ansible-lint
platforms:
  - name: test-aws-Centos8-sonarqube
    image: ami-0ed2ad9dc845b42b6
    platform: centos8
    instance_type: t3a.medium
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: centos
    groups:
      - rhel_family

  - name: test-aws-Centos7-sonarqube
    image: ami-9887c6e7
    platform: centos7
    instance_type: t3a.medium
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: centos
    groups:
      - rhel_family

#  - name: test-aws-Centos6-sonarqube
#    image: ami-1585c46a
#    platform: centos6
#    instance_type: m5.large
#    region: us-east-1
#    vpc_subnet_id: subnet-0f2b9cd66faea38af
#    assign_public_ip: false
#    spot_price: 0.05
#    security_group_name:
#      - default
#    wait_timeout: 1800
#    ssh_user: centos
#    groups:
#      - rhel_family

  - name: test-aws-Ubuntu18-sonarqube
    image: ami-012fd5eb46f56731f
    platform: ubuntu18
    instance_type: t3a.medium
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: ubuntu
    groups:
      - python3

#  - name: test-aws-Ubuntu16-sonarqube
#    image: ami-09677e0a6b14905b0
#    platform: ubuntu16
#    instance_type: t3a.medium
#    region: us-east-1
#    vpc_subnet_id: subnet-0f2b9cd66faea38af
#    assign_public_ip: false
#    spot_price: 0.04
#    security_group_name:
#      - default
#    wait_timeout: 1800
#    ssh_user: ubuntu
#    groups:
#      - python3

#  - name: test-aws-Debian10-sonarqube
#    image: ami-0dedf6a6502877301
#    platform: debian10
#    instance_type: m5.large
#    region: us-east-1
#    vpc_subnet_id: subnet-0f2b9cd66faea38af
#    assign_public_ip: false
#    spot_price: 0.05
#    security_group_name:
#      - default
#    wait_timeout: 1800
#    ssh_user: admin
#    groups:
#      - python3

#  - name: test-aws-Debian9-sonarqube
#    image: ami-003f19e0e687de1cd
#    platform: debian9
#    instance_type: m5.large
#    region: us-east-1
#    vpc_subnet_id: subnet-0f2b9cd66faea38af
#    assign_public_ip: false
#    spot_price: 0.05
#    security_group_name:
#      - default
#    wait_timeout: 1800
#    ssh_user: admin
#    groups:
#      - python3

#  - name: test-aws-Amazon2-sonarqube
#    image: ami-0b898040803850657
#    platform: amazon2
#    instance_type: m5.large
#    region: us-east-1
#    vpc_subnet_id: subnet-0f2b9cd66faea38af
#    assign_public_ip: false
#    spot_price: 0.05
#    security_group_name:
#      - default
#    wait_timeout: 1800
#    ssh_user: ec2-user
#    groups:
#      - rhel_family

#  - name: test-aws-Amazon-sonarqube
#    image: ami-035b3c7efe6d061d5
#    platform: amazon
#    instance_type: m5.large
#    region: us-east-1
#    vpc_subnet_id: subnet-0f2b9cd66faea38af
#    assign_public_ip: false
#    spot_price: 0.05
#    security_group_name:
#      - default
#    wait_timeout: 1800
#    ssh_user: ec2-user
#    groups:
#      - rhel_family

provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      callback_whitelist: profile_tasks,timer
  inventory:
    group_vars:
      python3:
        ansible_python_interpreter: /usr/bin/python3
  playbooks:
    create: ../resources/provisioning/AWS/create.yml
    prepare: ../resources/prepare.yml
    destroy: ../resources/provisioning/AWS/destroy.yml
    verify: ../resources/tests/verify.yml
scenario:
  name: cloud-aws-direct
verifier:
  name: ansible
