---
- name: Include common prepare
  import_playbook: provisioning/AWS/prepare.yml

- name: Check yum
  command: "python -c 'import yum, pprint; yb = yum.YumBase(); pprint.pprint(yb.conf.yumvar, width=1)'"

- name: Prepare pre-requisites
  hosts: all
  roles:
    - role: lean_delivery.java
      java_major_version: 11
      transport: repositories
    - role: anxs.postgresql
      become: true
      postgresql_users:
        - name: sonar
          pass: sonar
      postgresql_databases:
        - name: sonar
          owner: sonar
    - role: nginxinc.nginx
      become: true
    - role: jdauphant.ssl-certs
      become: true
      ssl_certs_path_owner: nginx
      ssl_certs_path_group: nginx
