---
- name: Prepare pre-requisites
  hosts: all
  strategy: mitogen_linear
  roles:
    - role: lean_delivery.java
      java_major_version: 8
      transport: repositories
    - role: anxs.postgresql
      become: true
      postgresql_users:
        - name: sonar
          pass: sonar
      postgresql_databases:
        - name: sonar
          owner: sonar
    - role: jdauphant.ssl-certs
      become: true
      ssl_certs_path_owner: root
      ssl_certs_path_group: root
      ssl_certs_mode: 0755
    - role: nginxinc.nginx
      become: true
