---
- name: Prepare
  hosts: all
  roles:
    - role: lean_delivery.java
      java_major_version: 8
      transport: repositories
    - role: anxs.postgresql
      become: true
      postgresql_users:
        - name: sonar
          pass: sonar
      postgresql_databases:
        - name: sonar
          owner: sonar
    - role: jdauphant.ssl-certs
      ssl_certs_path_owner: nginx
      ssl_certs_path_group: nginx
    - role: nginxinc.nginx
