---
- name: Include common prepare
  import_playbook: provisioning/AWS/prepare.yml

- name: Prepare pre-requisites
  hosts: all
  pre_tasks:
    - name: install epel
      package:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present
      when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'
  roles:
    - role: lean_delivery.java
      java_major_version: 11
      transport: repositories
    - role: anxs.postgresql
      become: true
      postgresql_users:
        - name: sonar
          pass: sonar
      postgresql_databases:
        - name: sonar
          owner: sonar
    - role: nginxinc.nginx
      become: true
    - role: jdauphant.ssl-certs
      become: true
      ssl_certs_path_owner: nginx
      ssl_certs_path_group: nginx
