---
- name: Prepare
  become: yes
  gather_facts: true
  hosts: all
  roles:
    - role: lean_delivery.java
      java_major_version: 11
      java_tarball_install: True
      transport: web
      transport_web: https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz
    - role: anxs.postgresql
      postgresql_users:
        - name: sonar
          pass: sonar
      postgresql_databases:
        - name: sonar
          owner: sonar
    - role: jdauphant.ssl-certs
      ssl_certs_common_name: '{{ ansible_fqdn }}'
      ssl_certs_path_owner: root
      ssl_certs_path_group: root
      ssl_certs_mode: 0755
    - role: nginxinc.nginx
    - role: gantsign.maven
