---
- name: Prepare pre-requisites
  hosts: all
  roles:
    - role: lean_delivery.java
      transport: web
      transport_web: https://download.java.net/java/GA/jdk17.0.2/dfd4a8d0985749f896bed50d7138ee7f/8/GPL/openjdk-17.0.2_linux-x64_bin.tar.gz
      java_tarball_install: true
# https://github.com/lean-delivery/ansible-role-sonarqube/issues/3025
#    - role: anxs.postgresql
#      become: true
#      postgresql_users:
#        - name: sonar
#          pass: sonar
#      postgresql_databases:
#        - name: sonar
#          owner: sonar
#    - role: nginxinc.nginx
#      become: true
#    - role: jdauphant.ssl-certs
#      become: true
#      ssl_certs_path_owner: nginx
#      ssl_certs_path_group: nginx
