---
- name: Include common prepare
  import_playbook: provisioning/AWS/prepare.yml

- name: Prepare pre-requisites
  hosts: all
  roles:
    - role: lean_delivery.java
      java_major_version: 11
      java_tarball_install: true
      transport: web
      transport_web: https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz
    - role: anxs.postgresql
      become: true
      postgresql_users:
        - name: sonar
          pass: sonar
      postgresql_databases:
        - name: sonar
          owner: sonar
    - role: nginxinc.nginx
      become: true
    - role: jdauphant.ssl-certs
      become: true
      ssl_certs_path_owner: nginx
      ssl_certs_path_group: nginx
