---
- name: Prepare pre-requisites
  hosts: all
  pre_tasks:
  roles:
    - role: lean_delivery.java
      java_major_version: 11
      transport: repositories
    - role: jdauphant.ssl-certs
      become: true
      ssl_certs_path_owner: nginx
      ssl_certs_path_group: nginx
