---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-docker-centos7-ansible-role-sonarqube
    image: leandelivery/docker-systemd:centos7
    privileged: True
    security_opts:
      - seccomp=unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
    capabilities:
      - SYS_ADMIN
    groups:
      # - sonarqube
      - rhel_family
provisioner:
  name: ansible
  log: False
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  options:
    verbose: True
  directory: ../resources/tests/
  lint:
    name: flake8
