---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint: |
  yamllint . -c .yamllint
  ansible-lint . -c .ansible-lint
platforms:
  - name: centos7
    image: leandelivery/docker-systemd:centos7
    privileged: true

  - name: ubuntu18.04
    image: leandelivery/docker-systemd:ubuntu-18.04
    privileged: true
    security_opts:
      - seccomp=unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
    capabilities:
      - SYS_ADMIN

  - name: ubuntu20.04
    image: leandelivery/docker-systemd:ubuntu-20.04
    privileged: true
    security_opts:
      - seccomp=unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
    capabilities:
      - SYS_ADMIN
provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      callback_whitelist: profile_tasks,timer
  inventory:
    group_vars:
      python3:
        ansible_python_interpreter: /usr/bin/python3
  playbooks:
    prepare: ../resources/prepare.yml
    verify: ../resources/tests/verify.yml
scenario:
  name: default
verifier:
  name: ansible
