---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-docker-ubuntu1804-sonarqube
    image: leandelivery/docker-systemd:ubuntu-18.04
    privileged: true
    security_opts:
      - seccomp=unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
    capabilities:
      - SYS_ADMIN
    groups:
      - debian_family
      - python3
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
  config_options:
    defaults:
      callback_whitelist: profile_tasks,timer
  inventory:
    group_vars:
      python3:
        ansible_python_interpreter: /usr/bin/python3
  playbooks:
    prepare: ../resources/prepare.yml
    verify: ../resources/tests/verify.yml
scenario:
  name: sonarqube-8.0
verifier:
  name: ansible
  lint:
    name: ansible-lint
