---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: delegated
lint: |
  yamllint
  ansible-lint
platforms:
  - name: test-epc-centos7-sonarqube
    image: CentOS7_64-bit
    shape: large
    region: EPAM-BY2
    wait_timeout: 3600
    groups:
      - rhel_family
  - name: test-epc-ubuntu1804-sonarqube
    image: Ubuntu18.04_64-bit
    shape: large
    region: EPAM-BY2
    wait_timeout: 3600
    groups:
      - python3
provisioner:
  name: ansible
  log: true
  inventory:
    group_vars:
      python3:
        ansible_python_interpreter: /usr/bin/python3
  playbooks:
    create: ../resources/provisioning/EPC/create.yml
    prepare: ../resources/prepare.yml
    destroy: ../resources/provisioning/EPC/destroy.yml
    verify: ../resources/tests/verify.yml
  config_options:
    ssh_connection:
      control_path: "/var/ans/%%h"
scenario:
  name: cloud-epc-delegated
verifier:
  name: ansible
  options:
    verbose: true
  directory: ../resources/tests/
