---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: delegated
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-epc-centos7-ansible-role-sonarqube
    image: CentOS7_64-bit
    shape: small
    region: EPAM-BY2
    wait_timeout: 3600
    groups:
      - rhel_family
provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      strategy_plugins: /tmp/molecule/plugins/mitogen/ansible_mitogen/plugins/strategy
    ssh_connection:
      control_path: '/var/ans/%%h'
  playbooks:
    create: ../resources/provisioning/EPC/create.yml
    prepare: ../resources/prepare.yml
    destroy: ../resources/provisioning/EPC/destroy.yml
  lint:
    name: ansible-lint
  env:
    ANSIBLE_LIBRARY: ${ANSIBLE_LIBRARY}
scenario:
  name: cloud-epc-delegated
verifier:
  name: testinfra
  options:
    verbose: true
  directory: ../resources/tests/
  lint:
    name: flake8
