---
- name: Converge
  hosts: all
  vars:
    ssl_certs_common_name: "{{ sonar_proxy_server_name }}"
  roles:
    - role: lean_delivery.java
    - role: ANXS.postgresql
      postgresql_users:
        - name: sonar
          pass: sonar
      postgresql_databases:
        - name: sonar
          owner: sonar
    - role: jdauphant.ssl-certs
      ssl_certs_common_name: "example.com"
      ssl_certs_path_owner: "root"
      ssl_certs_path_group: "root"
      ssl_certs_mode: "0755"
    - role: nginxinc.nginx
    - role: ansible-role-sonarqube
